export const CBSE_CLASS_XII_CORE_SUBJECTS = [
  { subject: "Accountancy", curriculum: "https://cbseacademic.nic.in/web_material/CurriculumMain26/SrSec/Accountancy_SrSec_2025-26.pdf", sqp: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/Accountancy-SQP.pdf", marking: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/Accountancy-MS.pdf" },
  { subject: "Biology", curriculum: "https://cbseacademic.nic.in/web_material/CurriculumMain26/SrSec/Biology_SrSec_2025-26.pdf", sqp: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/Biology-SQP.pdf", marking: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/Biology-MS.pdf" },
  { subject: "Business Studies", curriculum: "https://cbseacademic.nic.in/web_material/CurriculumMain26/SrSec/BusinessStudies_SrSec_2025-26.pdf", sqp: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/BusinessStudies-SQP.pdf", marking: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/BusinessStudies-MS.pdf" },
  { subject: "Chemistry", curriculum: "https://cbseacademic.nic.in/web_material/CurriculumMain26/SrSec/Chemistry_SrSec_2025-26.pdf", sqp: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/Chemistry-SQP.pdf", marking: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/Chemistry-MS.pdf" },
  { subject: "Computer Science", curriculum: "https://cbseacademic.nic.in/web_material/CurriculumMain26/SrSec/Computer_Science_SrSec_2025-26.pdf", sqp: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/ComputerScience-SQP.pdf", marking: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/ComputerScience-MS.pdf" },
  { subject: "Economics", curriculum: "https://cbseacademic.nic.in/web_material/CurriculumMain26/SrSec/Economics_SrSec_2025-26.pdf", sqp: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/Economics-SQP.pdf", marking: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/Economics-MS.pdf" },
  { subject: "English Core", curriculum: "https://cbseacademic.nic.in/web_material/CurriculumMain26/SrSec/English_core_SrSec_2025-26.pdf", sqp: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/EnglishCore-SQP.pdf", marking: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/EnglishCore-MS.pdf" },
  { subject: "Mathematics", curriculum: "https://cbseacademic.nic.in/web_material/CurriculumMain26/SrSec/Maths_SrSec_2025-26.pdf", sqp: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/Maths-SQP.pdf", marking: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/Maths-MS.pdf" },
  { subject: "Physics", curriculum: "https://cbseacademic.nic.in/web_material/CurriculumMain26/SrSec/Physics_SrSec_2025-26.pdf", sqp: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/Physics-SQP.pdf", marking: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/Physics-MS.pdf" },
  { subject: "Political Science", curriculum: "https://cbseacademic.nic.in/web_material/CurriculumMain26/SrSec/PoliticalScience_SrSec_2025-26.pdf", sqp: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/PolSci-SQP.pdf", marking: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/PolSci-MS.pdf" },
] as const;
