import { motion } from "framer-motion";
import { ArrowRight, CheckCircle2, FileScan, Gauge, Gavel, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { useEffect, useRef, useState } from "react";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);

function Metric({ target, label, suffix = "" }: { target: number; label: string; suffix?: string }) {
  const [value, setValue] = useState(0);
  useEffect(() => { let frame = 0; const start = performance.now(); const tick = (time: number) => { const progress = Math.min(1, (time - start) / 1150); setValue(Math.floor(target * (1 - (1 - progress) ** 3))); if (progress < 1) frame = requestAnimationFrame(tick); }; frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame); }, [target]);
  return <div><p className="font-display text-4xl text-[#1c1917] sm:text-5xl">{value.toLocaleString()}{suffix}</p><p className="mono-label mt-2 text-[#78716c]">{label}</p></div>;
}

const stages = [
  { n: "01", title: "Scan intake", detail: "Booklet & paper paired", icon: FileScan },
  { n: "02", title: "Clarity gate", detail: "Page-level edge check", icon: Gauge },
  { n: "03", title: "AI evaluation", detail: "Scheme-bound marks", icon: Sparkles },
  { n: "04", title: "Moderation", detail: "Deviation audit trail", icon: Gavel },
];

export default function Landing() {
  const root = useRef<HTMLDivElement>(null);
  useGSAP(() => {
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    gsap.to(".hero-scan", { xPercent: 195, duration: 2.6, ease: "power2.inOut", repeat: -1, yoyo: true });
  }, { scope: root });
  return <div ref={root} className="grain min-h-screen overflow-hidden bg-[#fafaf9] text-[#1c1917]">
    <header className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8"><Link href="/" className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#1c1917] font-display text-xl text-[#e6c075]">D</span><span className="font-display text-3xl leading-none">Drishti</span></Link><nav className="hidden items-center gap-7 text-sm md:flex"><a className="nav-link" href="#workflow">Workflow</a><a className="nav-link" href="#controls">Controls</a><a className="nav-link" href="#record">Record</a></nav><Link href="/login" className="press rounded-full bg-[#1c1917] px-4 py-2.5 text-sm font-medium text-white">Enter a desk</Link></header>
    <main>
      <section className="dot-grid relative border-y border-[#e7e4df]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_28%,rgba(230,192,117,.22),transparent_28%),radial-gradient(circle_at_18%_78%,rgba(232,228,216,.8),transparent_24%)]"/><div className="relative mx-auto grid min-h-[620px] max-w-7xl items-center gap-14 px-5 py-16 sm:px-8 lg:grid-cols-[1.1fr_.9fr] lg:py-24"><div><motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .45 }} className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#16803d]"/><span className="mono-label text-[#7c5e10]">Forensic evaluation environment</span></motion.div><motion.h1 initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .55, delay: .06 }} className="mt-6 max-w-3xl font-display text-[clamp(3.7rem,8vw,7rem)] leading-[.82] tracking-[-.045em]">The mark is only the <em className="font-display-italic text-[#7c5e10]">beginning.</em></motion.h1><motion.p initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .5, delay: .16 }} className="mt-8 max-w-xl text-base leading-7 text-[#57534e]">Drishti turns a scanned answer booklet into a reviewable, scheme-bound evidence trail. Human judgement remains in control; AI highlights what deserves a second look.</motion.p><motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .5, delay: .24 }} className="mt-9 flex flex-wrap items-center gap-3"><Link href="/login" className="press flex items-center gap-2 rounded-full bg-[#1c1917] px-5 py-3.5 text-sm font-semibold text-white">Start at the control desk <ArrowRight size={16}/></Link><a href="#workflow" className="press rounded-full border border-[#d6d3cd] bg-white px-5 py-3.5 text-sm font-medium">Inspect workflow</a></motion.div></div>
        <motion.div initial={{ opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .7, delay: .14, ease: [0.23, 1, 0.32, 1] }} className="float-soft forensic-border panel relative mx-auto w-full max-w-[460px] overflow-hidden rounded-[2rem] p-5"><div className="flex items-center justify-between border-b border-[#ece8df] pb-4"><div><p className="mono-label text-[#a8a29e]">Live bundle state</p><p className="mt-1 font-display text-2xl">Candidate record 026</p></div><span className="rounded-full bg-[#dff5e7] px-2.5 py-1 mono-label text-[#16803d]">clear</span></div><div className="relative mt-5 aspect-[4/3] overflow-hidden rounded-2xl bg-[#ece7dd] p-5"><div className="absolute left-[-100%] top-1/2 h-px w-1/2 bg-[#e6c075] shadow-[0_0_15px_5px_rgba(230,192,117,.38)]"><div className="hero-scan h-full w-full bg-[#fff6d3]"/></div><div className="flex h-full flex-col justify-between rounded-lg border border-[#d7d1c4] bg-[#f9f8f4] p-4"><div className="flex justify-between"><span className="h-2 w-16 rounded bg-[#d2ccc0]"/><span className="h-2 w-7 rounded bg-[#d2ccc0]"/></div><div className="space-y-2"><div className="h-1.5 w-full rounded bg-[#dad4c8]"/><div className="h-1.5 w-[82%] rounded bg-[#ded8ce]"/><div className="h-1.5 w-[91%] rounded bg-[#ded8ce]"/><div className="h-1.5 w-[65%] rounded bg-[#ded8ce]"/></div><div className="flex items-end justify-between"><div className="h-8 w-8 rounded-full border-2 border-[#16803d]"/><span className="mono-label text-[#78716c]">Page 04 / 08</span></div></div></div><div className="mt-5 grid grid-cols-3 gap-2"><div className="rounded-xl bg-[#f9f7f2] p-3"><p className="mono-label text-[#a8a29e]">Questions</p><p className="mt-2 text-sm font-semibold">80 marks</p></div><div className="rounded-xl bg-[#f9f7f2] p-3"><p className="mono-label text-[#a8a29e]">AI score</p><p className="mt-2 text-sm font-semibold">62 / 80</p></div><div className="rounded-xl bg-[#f9f7f2] p-3"><p className="mono-label text-[#a8a29e]">Variance</p><p className="mt-2 text-sm font-semibold">Open</p></div></div></motion.div></div></section>
      <section id="record" className="mx-auto grid max-w-7xl gap-8 px-5 py-16 sm:grid-cols-3 sm:px-8 lg:py-20"><Metric target={100} suffix="%" label="scheme clamping"/><Metric target={3} label="mark deviation gate"/><Metric target={12} suffix="h" label="role-session record"/></section>
      <section id="workflow" className="border-y border-[#e7e4df] bg-white"><div className="reveal-on-scroll mx-auto max-w-7xl px-5 py-16 sm:px-8"><div className="max-w-2xl"><p className="mono-label text-[#7c5e10]">Chain of custody</p><h2 className="mt-4 font-display text-5xl leading-none">Every decision leaves a trail.</h2></div><div className="mt-12 grid gap-px overflow-hidden rounded-2xl border border-[#e7e4df] bg-[#e7e4df] md:grid-cols-4">{stages.map(stage => <div key={stage.n} className="bg-white p-6"><div className="flex items-center justify-between"><span className="mono-label text-[#c5a45c]">{stage.n}</span><stage.icon size={18} className="text-[#7c5e10]"/></div><h3 className="mt-10 text-lg font-semibold">{stage.title}</h3><p className="mt-2 text-sm leading-6 text-[#78716c]">{stage.detail}</p></div>)}</div></div></section>
      <section id="controls" className="reveal-on-scroll mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:px-8 lg:grid-cols-2 lg:py-24"><div><p className="mono-label text-[#7c5e10]">Designed for accountable grading</p><h2 className="mt-4 font-display text-5xl leading-none">Automation with a human right of reply.</h2></div><div className="space-y-5">{[["Page-level clarity gates", "A low variance-of-Laplacian reading is surfaced before the booklet reaches a marker."], ["Strict score denominator", "Printed paper total wins. An operator total follows; catalog fallback remains explicitly incomplete."], ["Moderated divergence", "A gap of three or more marks becomes an auditable deviation—not a silent overwrite."]].map(([title, body]) => <div key={title} className="flex gap-4"><CheckCircle2 className="mt-1 shrink-0 text-[#16803d]" size={18}/><p className="text-sm leading-6 text-[#57534e]"><strong className="text-[#1c1917]">{title}.</strong> {body}</p></div>)}</div></section>
    </main><footer className="border-t border-[#e7e4df] px-5 py-8 sm:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between"><span className="font-display text-2xl">Drishti</span><span className="mono-label text-[#a8a29e]">Examination intelligence · traceable by design</span></div></footer>
  </div>;
}
