import { type DrishtiRole } from "@shared/drishti";
import { writeRoleSession } from "@/lib/session";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, ArrowRight, ClipboardCheck, Gavel, ScanLine, ShieldCheck } from "lucide-react";
import { useLocation } from "wouter";

const roles: { role: DrishtiRole; label: string; description: string; icon: typeof ScanLine; access: string }[] = [
  { role: "operator", label: "Operator", description: "Intake, scan review, page replacement and finalization.", icon: ScanLine, access: "Intake desk" },
  { role: "evaluator", label: "Evaluator", description: "Marking workspace, AI grading and second-reader requests.", icon: ClipboardCheck, access: "Marking desk" },
  { role: "moderator", label: "Moderator", description: "Deviation resolution, audit controls and re-evaluation decisions.", icon: Gavel, access: "Moderation desk" },
  { role: "admin", label: "Administrator", description: "Complete oversight, configuration and protected data-console access.", icon: ShieldCheck, access: "Full control" },
];

export default function Login() {
  const [, setLocation] = useLocation(); const selectRole = trpc.session.selectRole.useMutation({ onSuccess: result => { writeRoleSession(result.token, result.session); setLocation("/dashboard"); } });
  return <main className="grain dot-grid grid min-h-screen place-items-center bg-[#fafaf9] px-5 py-10"><div className="w-full max-w-5xl"><button onClick={() => setLocation("/")} className="press mb-10 flex items-center gap-2 text-sm text-[#78716c] hover:text-[#1c1917]"><ArrowLeft size={16}/>Return to the record</button><div className="grid overflow-hidden rounded-[2rem] border border-[#e7e4df] bg-white shadow-[0_22px_60px_rgba(55,45,30,.09)] lg:grid-cols-[.78fr_1.22fr]"><section className="relative overflow-hidden bg-[#1c1917] p-8 text-white sm:p-10"><div className="absolute -right-20 -top-20 h-52 w-52 rounded-full bg-[#e6c075]/15 blur-2xl"/><div className="relative"><span className="grid h-10 w-10 place-items-center rounded-full border border-[#e6c075]/50 font-display text-2xl text-[#e6c075]">D</span><p className="mono-label mt-16 text-[#e6c075]">Role-gated access</p><h1 className="mt-4 font-display text-5xl leading-[.9]">Choose your examination desk.</h1><p className="mt-6 max-w-sm text-sm leading-6 text-[#d6d3d1]">No password is requested. Your selected role creates a signed session that expires exactly twelve hours after entry.</p><div className="mt-14 border-t border-white/15 pt-5"><p className="mono-label text-[#a8a29e]">Session scope</p><p className="mt-2 text-sm text-[#f5f5f4]">Permissions are verified again on every protected operation.</p></div></div></section><section className="p-7 sm:p-10"><p className="mono-label text-[#7c5e10]">Identity selection</p><h2 className="mt-3 font-display text-4xl">Which record are you responsible for?</h2><div className="mt-8 grid gap-3 sm:grid-cols-2">{roles.map(item => <button key={item.role} disabled={selectRole.isPending} data-testid={`role-${item.role}`} onClick={() => selectRole.mutate({ role: item.role })} className="role-card press group rounded-2xl border border-[#e7e4df] bg-[#fff] p-5 text-left disabled:cursor-wait disabled:opacity-60"><div className="flex items-start justify-between"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#f7f1e3] text-[#7c5e10]"><item.icon size={18}/></span><ArrowRight size={16} className="text-[#c8c2b8] transition-transform group-hover:translate-x-1"/></div><p className="mt-7 font-semibold">{item.label}</p><p className="mt-1 mono-label text-[#a8a29e]">{item.access}</p><p className="mt-3 text-xs leading-5 text-[#78716c]">{item.description}</p></button>)}</div>{selectRole.error && <p className="mt-5 rounded-xl bg-[#fae2df] px-4 py-3 text-sm text-[#c0392b]">{selectRole.error.message}</p>}</section></div></div></main>;
}
